### ISSUE TITLE
Copyright / License

### ISSUE THREAD

**Issue by oskarpearson** [mxgxw/MFRC522-python#5]
Hi - Thanks for a useful module.

 Could I trouble you to add some indication of the license / copyright to this project?

It seems that the original Arduino code might be under Apache v2 - if this is a port of https://github.com/JoyLabs/arduino

I'm interested in using the code as part of https://github.com/oskarpearson/raspberry-pi-access-control-system but would prefer to license clarity before I do so.

Thanks!

Oskar

**Comment by glogiotatidis** [comment]
+1 for a license. Thanks!

**Comment by LudwigKnuepfer** [comment]
@mxgxw ping
